[package]
name = "love_equinox"
version = "0.2.0"
edition = "2021"
authors = ["Normthenord"]
description = "A library for calculating your Love Equinox"
license = "MIT"

[dependencies]
time = "0.3.36"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3